{
  "name": "try-invoke",
  "version": "1.0.0",
  "description": "Attempts to invoke the given function, returning either the result or the caught error object.",
  "main": "index.js",
  "scripts": {
    "lint": "jshint index.js",
    "pretest": "npm run lint",
    "test": "mocha -R spec",
    "test:cov": "rm -rf ./test/coverage && istanbul cover _mocha --dir ./test/coverage -- -R spec",
    "test:rpt": "npm run test:cov && coveralls < ./test/coverage/lcov.info",
    "prepublish": "npm test"
  },
  "keywords": [
    "invoke",
    "execute",
    "call",
    "apply",
    "function",
    "exception",
    "error"
  ],
  "license": "MIT",
  "author": {
    "name": "bubkoo",
    "email": "bubkoo.wy@gmail.com"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gearcase/try-invoke.git"
  },
  "bugs": {
    "url": "https://github.com/gearcase/try-invoke/issues"
  },
  "homepage": "https://github.com/gearcase/try-invoke#readme",
  "devDependencies": {
    "jshint": "^2.9.1",
    "chai": "^3.5.0",
    "coveralls": "^2.11.9",
    "istanbul": "^0.4.2",
    "mocha": "^2.4.5"
  },
  "dependencies": {
    "invoke-fn": "^1.0.0",
    "is-error": "^2.2.0"
  }
}
